import type {
  SiteAssetExposure,
  PrecursorFilterOption,
  ExposureTrendPoint,
} from '../types/safety';

export const MOCK_PRECURSOR_FILTER_OPTIONS: PrecursorFilterOption[] = [
  {
    id: 'ALL',
    title: 'All Active Precursors',
    rule: 'Energy Isolation',
    connectedReportsCount: 22,
    affectedAssetsCount: 6,
  },
  {
    id: 'PREC-04-ENERGY-ISO',
    title: 'High-Pressure Energy Isolation Bypass',
    rule: 'Energy Isolation',
    connectedReportsCount: 7,
    affectedAssetsCount: 4,
  },
  {
    id: 'PREC-02-LINE-FIRE',
    title: 'Line of Fire During Tubular Handling',
    rule: 'Line of Fire',
    connectedReportsCount: 5,
    affectedAssetsCount: 3,
  },
  {
    id: 'PREC-07-CONFINED-SPACE',
    title: 'Confined Space Without Live Gas Testing',
    rule: 'Confined Space',
    connectedReportsCount: 4,
    affectedAssetsCount: 2,
  },
  {
    id: 'PREC-09-WORKING-HEIGHT',
    title: 'Derrick Working at Height 100% Tie-Off',
    rule: 'Working at Height',
    connectedReportsCount: 2,
    affectedAssetsCount: 2,
  },
];

export const MOCK_SITE_EXPOSURES: SiteAssetExposure[] = [
  {
    siteId: 'site-duliajan-14',
    siteName: 'Duliajan Deep Drill Rig #14',
    clusterArea: 'Duliajan Operational Hub',
    assetClass: 'Drilling Rig',
    totalObservations: 42,
    sifPotentialCount: 8,
    nonSifCount: 34,
    precursorDensityPercent: 19.0,
    dominantPrecursorId: 'PREC-04-ENERGY-ISO',
    dominantPrecursorTitle: 'High-Pressure Energy Isolation & Zero-Verification Bypass',
    lifeSavingRule: 'Energy Isolation',
    failedBarrier: 'Positive Physical Isolation & Bleed-off Verification',
    trend: 'INCREASING',
    connectedReportIds: ['OIL-UA-2026-0842', 'OIL-UA-2026-0867'],
    activities: [
      { activityName: 'Mud pump fluid end overhaul', count: 12 },
      { activityName: 'Drill pipe tripping operations', count: 15 },
      { activityName: 'BOP accumulator check valve servicing', count: 8 },
      { activityName: 'Rig floor deck maintenance', count: 7 },
    ],
    spatialPosition: { gridX: 38, gridY: 28 },
  },
  {
    siteId: 'site-moran-07',
    siteName: 'Moran Workover Rig #07',
    clusterArea: 'Moran Field Operations',
    assetClass: 'Workover Rig',
    totalObservations: 18,
    sifPotentialCount: 6,
    nonSifCount: 12,
    precursorDensityPercent: 33.3, // HIGH CONCENTRATION OUTLIER
    dominantPrecursorId: 'PREC-04-ENERGY-ISO',
    dominantPrecursorTitle: 'High-Pressure Energy Isolation & Zero-Verification Bypass',
    lifeSavingRule: 'Energy Isolation',
    failedBarrier: 'Positive Physical Isolation & Bleed-off Verification',
    trend: 'INCREASING',
    connectedReportIds: ['OIL-UA-2026-0849', 'OIL-UA-2026-0873'],
    activities: [
      { activityName: 'Rotary kelly hose hammer union break', count: 6 },
      { activityName: 'Mud tank agitator drive inspection', count: 4 },
      { activityName: 'Tubing rod tripping', count: 5 },
      { activityName: 'Suction pit sludge clearing', count: 3 },
    ],
    spatialPosition: { gridX: 18, gridY: 62 },
  },
  {
    siteId: 'site-digboi-ocs2',
    siteName: 'Digboi Oil Collection Station (OCS-2)',
    clusterArea: 'Digboi Production Sector',
    assetClass: 'Oil Processing Plant',
    totalObservations: 34,
    sifPotentialCount: 7,
    nonSifCount: 27,
    precursorDensityPercent: 20.6,
    dominantPrecursorId: 'PREC-04-ENERGY-ISO',
    dominantPrecursorTitle: 'High-Pressure Energy Isolation & Zero-Verification Bypass',
    lifeSavingRule: 'Energy Isolation',
    failedBarrier: 'Positive Physical Isolation & Bleed-off Verification',
    trend: 'STABLE',
    connectedReportIds: ['OIL-UA-2026-0855', 'OIL-UA-2026-0880'],
    activities: [
      { activityName: 'Test separator inlet manifold bolting', count: 11 },
      { activityName: '16-inch crude pipeline pig receiving', count: 9 },
      { activityName: 'High-pressure gas manifold valve repacking', count: 8 },
      { activityName: 'Transfer pump mechanical seal check', count: 6 },
    ],
    spatialPosition: { gridX: 82, gridY: 34 },
  },
  {
    siteId: 'site-nhk-11',
    siteName: 'Naharkatiya Wellhead #11',
    clusterArea: 'Naharkatiya & Surrounding Wells',
    assetClass: 'Wellhead Installation',
    totalObservations: 12,
    sifPotentialCount: 3,
    nonSifCount: 9,
    precursorDensityPercent: 25.0,
    dominantPrecursorId: 'PREC-04-ENERGY-ISO',
    dominantPrecursorTitle: 'High-Pressure Energy Isolation & Zero-Verification Bypass',
    lifeSavingRule: 'Energy Isolation',
    failedBarrier: 'Positive Physical Isolation & Bleed-off Verification',
    trend: 'INCREASING',
    connectedReportIds: ['OIL-UA-2026-0861'],
    activities: [
      { activityName: 'Christmas tree gland nut tightening', count: 6 },
      { activityName: 'Wellhead shut-in pressure logging', count: 4 },
      { activityName: 'Surface wing valve choke adjustment', count: 2 },
    ],
    spatialPosition: { gridX: 52, gridY: 55 },
  },
  {
    siteId: 'site-duliajan-gcs3',
    siteName: 'Gas Compression Station #03',
    clusterArea: 'Duliajan Operational Hub',
    assetClass: 'Gas Compression',
    totalObservations: 26,
    sifPotentialCount: 4,
    nonSifCount: 22,
    precursorDensityPercent: 15.4,
    dominantPrecursorId: 'PREC-07-CONFINED-SPACE',
    dominantPrecursorTitle: 'Confined Space Entry Without Live Gas Testing',
    lifeSavingRule: 'Confined Space',
    failedBarrier: 'Continuous Atmospheric Gas Testing & Dedicated Standby Observer',
    trend: 'STABLE',
    connectedReportIds: [],
    activities: [
      { activityName: 'Scrubber separator internal baffle wash', count: 9 },
      { activityName: 'Reciprocating compressor cylinder check', count: 8 },
      { activityName: 'Gas cooler bundle inspection', count: 5 },
      { activityName: 'Suction strainer flange cleaning', count: 4 },
    ],
    spatialPosition: { gridX: 44, gridY: 18 },
  },
  {
    siteId: 'site-moran-yard',
    siteName: 'Moran Central Workover Yard & Pipe Depot',
    clusterArea: 'Moran Field Operations',
    assetClass: 'Workover Rig',
    totalObservations: 38,
    sifPotentialCount: 2,
    nonSifCount: 36,
    precursorDensityPercent: 5.3, // LOW DENSITY DESPITE HIGH VOLUME
    dominantPrecursorId: 'PREC-02-LINE-FIRE',
    dominantPrecursorTitle: 'Line of Fire During Heavy Tubular Handling',
    lifeSavingRule: 'Line of Fire',
    failedBarrier: 'Exclusion Zone Barricading & Standoff Protocols',
    trend: 'DECREASING',
    connectedReportIds: [],
    activities: [
      { activityName: 'Tubular casing loading onto flatbeds', count: 18 },
      { activityName: 'Drill collar thread cleaning and gauging', count: 12 },
      { activityName: 'Yard forklift and crane transit', count: 8 },
    ],
    spatialPosition: { gridX: 24, gridY: 78 },
  },
];

export const MOCK_EXPOSURE_TRENDS: Record<'7d' | '30d' | '90d', ExposureTrendPoint[]> = {
  '7d': [
    { timeLabel: '17 Sep', sifCount: 2, routineCount: 14 },
    { timeLabel: '18 Sep', sifCount: 3, routineCount: 18 },
    { timeLabel: '19 Sep', sifCount: 1, routineCount: 16 },
    { timeLabel: '20 Sep', sifCount: 4, routineCount: 22 },
    { timeLabel: '21 Sep', sifCount: 3, routineCount: 19 },
    { timeLabel: '22 Sep', sifCount: 5, routineCount: 25 },
    { timeLabel: '23 Sep', sifCount: 4, routineCount: 21 },
  ],
  '30d': [
    { timeLabel: 'Week 1 (25-31 Aug)', sifCount: 8, routineCount: 68 },
    { timeLabel: 'Week 2 (01-07 Sep)', sifCount: 11, routineCount: 74 },
    { timeLabel: 'Week 3 (08-14 Sep)', sifCount: 14, routineCount: 82 },
    { timeLabel: 'Week 4 (15-21 Sep)', sifCount: 19, routineCount: 91 },
    { timeLabel: 'Current Week', sifCount: 16, routineCount: 78 },
  ],
  '90d': [
    { timeLabel: 'July 2026', sifCount: 38, routineCount: 312 },
    { timeLabel: 'August 2026', sifCount: 52, routineCount: 388 },
    { timeLabel: 'September 2026', sifCount: 68, routineCount: 442 },
  ],
};
