"""PDF Generation Service for Executive Safety Briefs and Incident Dossiers (Phase 15).

Generates professional, enterprise-grade PDF documents using ReportLab.
Features custom canvas page-numbering, OIL India branding, structured tables,
KPI metric grids, and robust text-wrapping for safety reports.
"""

import io
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    HRFlowable,
    KeepTogether,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.db.models.action import HSEActionRecommendation
from app.db.models.assessment import SIFAssessment
from app.db.models.case import HSECase, HSECaseEvent, HSECaseSourceAssociation
from app.db.models.report import SafetyReport
from app.schemas.command_center import (
    ActionOverviewDTO,
    CommandCenterOverview,
    ConcentrationOverviewDTO,
    LSROverviewDTO,
    PrecursorOverviewDTO,
    SIFOverviewDTO,
)


class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas to dynamically compute and print total page count."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#4B5563"))

        # Header (pages 2+)
        if self._pageNumber > 1:
            self.drawString(54, 750, "OIL INDIA LIMITED — HSE SIF SENTINEL INTELLIGENCE")
            self.drawRightString(558, 750, "CONFIDENTIAL / INTERNAL USE ONLY")
            self.setStrokeColor(colors.HexColor("#D1D5DB"))
            self.setLineWidth(0.5)
            self.line(54, 744, 558, 744)

        # Footer (all pages)
        self.setStrokeColor(colors.HexColor("#D1D5DB"))
        self.setLineWidth(0.5)
        self.line(54, 45, 558, 45)

        footer_text = f"Generated by OIL SIF Sentinel AI Engine • {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}"
        self.drawString(54, 32, footer_text)
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 32, page_str)
        self.restoreState()


class PDFExportService:
    """Enterprise PDF generation engine for executive summaries and detailed dossiers."""

    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()

    def _setup_custom_styles(self):
        # Color Palette
        self.c_primary = colors.HexColor("#0B3B60")    # Deep Oil India Navy
        self.c_secondary = colors.HexColor("#E06A3B")  # SIF Orange/Amber
        self.c_dark = colors.HexColor("#1F2937")       # Charcoal Body Text
        self.c_muted = colors.HexColor("#6B7280")      # Muted Gray
        self.c_light_bg = colors.HexColor("#F3F4F6")   # Card background
        self.c_accent_bg = colors.HexColor("#EFF6FF")  # Light blue table header
        self.c_sif_red = colors.HexColor("#DC2626")    # Critical Red
        self.c_warn_amber = colors.HexColor("#D97706") # Warning Amber
        self.c_safe_green = colors.HexColor("#059669") # Safe Green

        # Typography Styles
        self.styles.add(ParagraphStyle(
            name="DocTitle",
            parent=self.styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=20,
            leading=24,
            textColor=self.c_primary,
            alignment=TA_LEFT,
        ))

        self.styles.add(ParagraphStyle(
            name="DocSubtitle",
            parent=self.styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=11,
            leading=15,
            textColor=self.c_secondary,
            alignment=TA_LEFT,
        ))

        self.styles.add(ParagraphStyle(
            name="SectionHeading",
            parent=self.styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=13,
            leading=17,
            textColor=self.c_primary,
            spaceBefore=14,
            spaceAfter=6,
            keepWithNext=True,
        ))

        self.styles.add(ParagraphStyle(
            name="SubSectionHeading",
            parent=self.styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=10,
            leading=14,
            textColor=self.c_dark,
            spaceBefore=8,
            spaceAfter=4,
            keepWithNext=True,
        ))

        self.styles.add(ParagraphStyle(
            name="BodyDark",
            parent=self.styles["Normal"],
            fontName="Helvetica",
            fontSize=9,
            leading=12,
            textColor=self.c_dark,
            alignment=TA_LEFT,
        ))

        self.styles.add(ParagraphStyle(
            name="BodyDarkJustify",
            parent=self.styles["Normal"],
            fontName="Helvetica",
            fontSize=9,
            leading=13,
            textColor=self.c_dark,
            alignment=TA_JUSTIFY,
        ))

        self.styles.add(ParagraphStyle(
            name="MetaLabel",
            parent=self.styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=8,
            leading=11,
            textColor=self.c_muted,
        ))

        self.styles.add(ParagraphStyle(
            name="MetaValue",
            parent=self.styles["Normal"],
            fontName="Helvetica",
            fontSize=8.5,
            leading=11,
            textColor=self.c_dark,
        ))

        self.styles.add(ParagraphStyle(
            name="TableHead",
            parent=self.styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=8.5,
            leading=11,
            textColor=self.c_primary,
            alignment=TA_LEFT,
        ))

        self.styles.add(ParagraphStyle(
            name="TableCell",
            parent=self.styles["Normal"],
            fontName="Helvetica",
            fontSize=8,
            leading=10.5,
            textColor=self.c_dark,
            alignment=TA_LEFT,
        ))

        self.styles.add(ParagraphStyle(
            name="TableCellCenter",
            parent=self.styles["Normal"],
            fontName="Helvetica",
            fontSize=8,
            leading=10.5,
            textColor=self.c_dark,
            alignment=TA_CENTER,
        ))

        self.styles.add(ParagraphStyle(
            name="KPITitle",
            parent=self.styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=8,
            leading=10,
            textColor=self.c_muted,
            alignment=TA_CENTER,
        ))

        self.styles.add(ParagraphStyle(
            name="KPIValue",
            parent=self.styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=15,
            leading=18,
            textColor=self.c_primary,
            alignment=TA_CENTER,
        ))

    def _build_header_banner(self, title: str, subtitle: str, metadata_items: List[tuple]) -> List[Any]:
        """Create a standardized enterprise document header banner."""
        elements = []
        elements.append(Paragraph(title, self.styles["DocTitle"]))
        elements.append(Spacer(1, 2))
        elements.append(Paragraph(subtitle, self.styles["DocSubtitle"]))
        elements.append(Spacer(1, 8))

        # Metadata table
        meta_data = []
        row = []
        for i, (label, val) in enumerate(metadata_items):
            cell_content = [
                Paragraph(label.upper(), self.styles["MetaLabel"]),
                Paragraph(str(val), self.styles["MetaValue"]),
            ]
            row.append(cell_content)
            if len(row) == 4 or i == len(metadata_items) - 1:
                while len(row) < 4:
                    row.append("")
                meta_data.append(row)
                row = []

        col_w = 504 / 4
        t = Table(meta_data, colWidths=[col_w] * 4)
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), self.c_light_bg),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#D1D5DB")),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 10))
        return elements

    # -------------------------------------------------------------------------
    # 1. EXECUTIVE SAFETY BRIEF PDF
    # -------------------------------------------------------------------------
    def generate_executive_safety_brief_pdf(
        self,
        overview: CommandCenterOverview,
        sif_overview: SIFOverviewDTO,
        precursor_overview: PrecursorOverviewDTO,
        concentration_overview: ConcentrationOverviewDTO,
        action_overview: ActionOverviewDTO,
        lsr_overview: LSROverviewDTO,
        filter_params: Optional[Dict[str, Any]] = None,
    ) -> bytes:
        """Generate high-level Executive Safety Brief PDF."""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            leftMargin=54,
            rightMargin=54,
            topMargin=54,
            bottomMargin=54,
        )

        elements = []

        # Document Header
        meta_items = [
            ("Generated At", overview.generated_at.strftime("%Y-%m-%d %H:%M UTC")),
            ("Data Baseline", overview.data_as_of.strftime("%Y-%m-%d %H:%M UTC")),
            ("Scope", "Corporate HSE Fleet"),
            ("Classification", "OIL Restricted"),
        ]
        if filter_params:
            if filter_params.get("location"):
                meta_items.append(("Location Filter", str(filter_params["location"])))
            if filter_params.get("from_date"):
                meta_items.append(("From Date", str(filter_params["from_date"])))
            if filter_params.get("to_date"):
                meta_items.append(("To Date", str(filter_params["to_date"])))

        elements.extend(self._build_header_banner(
            title="OIL INDIA LIMITED",
            subtitle="HSE EXECUTIVE SAFETY BRIEF & SIF INTELLIGENCE REPORT",
            metadata_items=meta_items,
        ))

        # 1. KPI Metric Grid
        elements.append(Paragraph("1. Executive Operational Metrics", self.styles["SectionHeading"]))
        
        kpi_cells = [
            [
                [Paragraph("TOTAL REPORTS", self.styles["KPITitle"]), Paragraph(str(overview.total_reports), self.styles["KPIValue"])],
                [Paragraph("ASSESSMENTS", self.styles["KPITitle"]), Paragraph(str(overview.total_assessments), self.styles["KPIValue"])],
                [Paragraph("POTENTIAL SIF", self.styles["KPITitle"]), Paragraph(f"<font color='{self.c_sif_red.hexval()}'>{overview.potential_sif_count}</font>", self.styles["KPIValue"])],
                [Paragraph("NON-SIF", self.styles["KPITitle"]), Paragraph(str(overview.non_sif_count), self.styles["KPIValue"])],
            ],
            [
                [Paragraph("OPEN ACTIONS", self.styles["KPITitle"]), Paragraph(f"<font color='{self.c_warn_amber.hexval()}'>{overview.open_action_count}</font>", self.styles["KPIValue"])],
                [Paragraph("ACTIVE CASES", self.styles["KPITitle"]), Paragraph(str(overview.active_case_count), self.styles["KPIValue"])],
                [Paragraph("RECURRING PATTERNS", self.styles["KPITitle"]), Paragraph(str(overview.recurring_pattern_count), self.styles["KPIValue"])],
                [Paragraph("CONCENTRATIONS", self.styles["KPITitle"]), Paragraph(str(overview.concentration_count), self.styles["KPIValue"])],
            ]
        ]
        kpi_table = Table(kpi_cells, colWidths=[126] * 4)
        kpi_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
            ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#CBD5E1")),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]))
        elements.append(kpi_table)
        elements.append(Spacer(1, 10))

        # 2. SIF Severity & Classification Breakdown
        elements.append(Paragraph("2. SIF Screening & Severity Distribution", self.styles["SectionHeading"]))
        pot_sif_c = sif_overview.classification_counts.get("POTENTIAL_SIF", 0)
        non_sif_c = sif_overview.classification_counts.get("NON_SIF", 0)
        undet_c = sif_overview.classification_counts.get("UNDETERMINED", 0)

        sif_rows = [
            [
                Paragraph("Classification", self.styles["TableHead"]),
                Paragraph("Report Count", self.styles["TableHead"]),
                Paragraph("Percentage", self.styles["TableHead"]),
                Paragraph("Potential Consequence Tier", self.styles["TableHead"]),
            ],
            [
                Paragraph(f"<b>POTENTIAL SIF</b>", self.styles["TableCell"]),
                Paragraph(str(pot_sif_c), self.styles["TableCellCenter"]),
                Paragraph(f"{(pot_sif_c / max(1, overview.total_assessments) * 100):.1f}%", self.styles["TableCellCenter"]),
                Paragraph("High Energy / Barrier Failure exposure", self.styles["TableCell"]),
            ],
            [
                Paragraph("NON-SIF", self.styles["TableCell"]),
                Paragraph(str(non_sif_c), self.styles["TableCellCenter"]),
                Paragraph(f"{(non_sif_c / max(1, overview.total_assessments) * 100):.1f}%", self.styles["TableCellCenter"]),
                Paragraph("Routine low-energy observations", self.styles["TableCell"]),
            ],
            [
                Paragraph("UNDETERMINED", self.styles["TableCell"]),
                Paragraph(str(undet_c), self.styles["TableCellCenter"]),
                Paragraph(f"{(undet_c / max(1, overview.total_assessments) * 100):.1f}%", self.styles["TableCellCenter"]),
                Paragraph("Inconclusive narrative context", self.styles["TableCell"]),
            ],
        ]
        sif_t = Table(sif_rows, colWidths=[130, 80, 80, 214])
        sif_t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), self.c_accent_bg),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        elements.append(sif_t)
        elements.append(Spacer(1, 10))

        # 3. Top Recurring Precursor Patterns
        elements.append(Paragraph("3. Discovered Precursor Patterns (N ≥ 3)", self.styles["SectionHeading"]))
        if precursor_overview.top_patterns:
            pattern_rows = [
                [
                    Paragraph("Pattern Code", self.styles["TableHead"]),
                    Paragraph("Reports", self.styles["TableHead"]),
                    Paragraph("Hazard Class", self.styles["TableHead"]),
                    Paragraph("Barrier Degradation", self.styles["TableHead"]),
                ]
            ]
            for p in precursor_overview.top_patterns[:5]:
                pattern_rows.append([
                    Paragraph(f"<b>{p.pattern_code}</b>", self.styles["TableCell"]),
                    Paragraph(str(p.occurrence_count or p.supporting_report_count), self.styles["TableCellCenter"]),
                    Paragraph(p.hazard_category or "GENERAL_HAZARD", self.styles["TableCell"]),
                    Paragraph(p.failed_barrier_type or "OPERATIONAL_CONTROLS", self.styles["TableCell"]),
                ])
            pat_t = Table(pattern_rows, colWidths=[150, 60, 140, 154])
            pat_t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), self.c_accent_bg),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]))
            elements.append(pat_t)
        else:
            elements.append(Paragraph("<i>No recurring precursor patterns identified in current filter criteria.</i>", self.styles["BodyDark"]))
        elements.append(Spacer(1, 10))

        # 4. Active Risk Concentrations
        elements.append(Paragraph("4. Active Multi-Dimensional Risk Concentrations", self.styles["SectionHeading"]))
        if concentration_overview.items:
            conc_rows = [
                [
                    Paragraph("Dimension", self.styles["TableHead"]),
                    Paragraph("Concentration Value", self.styles["TableHead"]),
                    Paragraph("Occurrences", self.styles["TableHead"]),
                    Paragraph("Reports", self.styles["TableHead"]),
                    Paragraph("Trend", self.styles["TableHead"]),
                ]
            ]
            for c in concentration_overview.items[:6]:
                dim_str = c.dimension_type.value if hasattr(c.dimension_type, "value") else str(c.dimension_type)
                trend_str = c.observed_trend.value if hasattr(c.observed_trend, "value") else str(c.observed_trend)
                conc_rows.append([
                    Paragraph(dim_str, self.styles["TableCell"]),
                    Paragraph(f"<b>{c.dimension_value}</b>", self.styles["TableCell"]),
                    Paragraph(str(c.occurrence_count), self.styles["TableCellCenter"]),
                    Paragraph(str(c.distinct_report_count), self.styles["TableCellCenter"]),
                    Paragraph(trend_str, self.styles["TableCellCenter"]),
                ])
            conc_t = Table(conc_rows, colWidths=[100, 194, 70, 70, 70])
            conc_t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), self.c_accent_bg),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]))
            elements.append(conc_t)
        else:
            elements.append(Paragraph("<i>No active risk concentrations detected in current filter criteria.</i>", self.styles["BodyDark"]))
        elements.append(Spacer(1, 10))

        # 5. HSE Action Workload & Life-Saving Rules
        elements.append(Paragraph("5. HSE Action Workload & Priority Summary", self.styles["SectionHeading"]))
        open_c = action_overview.status_counts.get("OPEN", 0) + action_overview.status_counts.get("IN_PROGRESS", 0)
        comp_c = action_overview.status_counts.get("COMPLETED", 0)
        act_rows = [
            [
                Paragraph("Action Status", self.styles["TableHead"]),
                Paragraph("Count", self.styles["TableHead"]),
                Paragraph("Priority Split (Critical / High / Med / Low)", self.styles["TableHead"]),
            ],
            [
                Paragraph("OPEN / IN PROGRESS", self.styles["TableCell"]),
                Paragraph(str(open_c), self.styles["TableCellCenter"]),
                Paragraph(
                    f"Crit: {action_overview.priority_distribution.get('CRITICAL', 0)} | "
                    f"High: {action_overview.priority_distribution.get('HIGH', 0)} | "
                    f"Med: {action_overview.priority_distribution.get('MEDIUM', 0)} | "
                    f"Low: {action_overview.priority_distribution.get('LOW', 0)}",
                    self.styles["TableCell"]
                ),
            ],
            [
                Paragraph("COMPLETED", self.styles["TableCell"]),
                Paragraph(str(comp_c), self.styles["TableCellCenter"]),
                Paragraph("Resolved actions verified by HSE leadership", self.styles["TableCell"]),
            ],
        ]
        act_t = Table(act_rows, colWidths=[150, 70, 284])
        act_t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), self.c_accent_bg),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        elements.append(act_t)

        # Build Document
        doc.build(elements, canvasmaker=NumberedCanvas)
        return buffer.getvalue()

    # -------------------------------------------------------------------------
    # 2. SIF INCIDENT INVESTIGATION DOSSIER PDF
    # -------------------------------------------------------------------------
    def generate_incident_dossier_pdf(
        self,
        report: SafetyReport,
        assessment: Optional[SIFAssessment],
        lsr_mappings: Optional[List[Any]] = None,
        related_actions: Optional[List[HSEActionRecommendation]] = None,
        related_case: Optional[HSECase] = None,
    ) -> bytes:
        """Generate comprehensive SIF Incident Investigation Dossier PDF."""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            leftMargin=54,
            rightMargin=54,
            topMargin=54,
            bottomMargin=54,
        )

        elements = []

        # Document Header
        report_ref = getattr(report, "report_ref", None) or str(report.id)[:8].upper()
        event_dt = getattr(report, "event_timestamp", None) or getattr(report, "created_at", None)
        meta_items = [
            ("Report Ref", report_ref),
            ("Event Date", event_dt.strftime("%Y-%m-%d") if event_dt else "N/A"),
            ("Location", report.reported_location or "N/A"),
            ("Source Type", report.source_type.value if hasattr(report.source_type, 'value') else str(report.source_type)),
        ]
        elements.extend(self._build_header_banner(
            title="OIL INDIA LIMITED",
            subtitle=f"SIF INCIDENT INVESTIGATION DOSSIER — REF: {report_ref}",
            metadata_items=meta_items,
        ))

        # 1. Incident Narrative
        elements.append(Paragraph("1. Incident Observation Narrative", self.styles["SectionHeading"]))
        narrative_text = getattr(report, "raw_text", "No detailed narrative recorded.")
        narrative_box = Table([[Paragraph(narrative_text, self.styles["BodyDarkJustify"])]], colWidths=[504])
        narrative_box.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F9FAFB")),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#D1D5DB")),
            ("PADDING", (0, 0), (-1, -1), 8),
        ]))
        elements.append(narrative_box)
        elements.append(Spacer(1, 10))

        # 2. AI SIF Classification & Screening Assessment
        elements.append(Paragraph("2. SIF Screening & Precursor Assessment", self.styles["SectionHeading"]))
        if assessment:
            sif_class = assessment.sif_classification.value if hasattr(assessment.sif_classification, 'value') else str(assessment.sif_classification)
            sev_pot = assessment.potential_severity.value if hasattr(assessment.potential_severity, 'value') else str(assessment.potential_severity)
            
            sif_color = self.c_sif_red.hexval() if sif_class == "POTENTIAL_SIF" else self.c_primary.hexval()
            
            assess_rows = [
                [
                    Paragraph("SIF Classification", self.styles["TableHead"]),
                    Paragraph("Evidence Score", self.styles["TableHead"]),
                    Paragraph("Potential Severity", self.styles["TableHead"]),
                    Paragraph("Rule Match Score", self.styles["TableHead"]),
                ],
                [
                    Paragraph(f"<font color='{sif_color}'><b>{sif_class}</b></font>", self.styles["TableCell"]),
                    Paragraph(f"{assessment.evidence_score:.2f}", self.styles["TableCellCenter"]),
                    Paragraph(sev_pot, self.styles["TableCell"]),
                    Paragraph(f"{assessment.rule_based_screening_score:.2f}", self.styles["TableCellCenter"]),
                ]
            ]
            assess_t = Table(assess_rows, colWidths=[140, 100, 140, 124])
            assess_t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), self.c_accent_bg),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]))
            elements.append(assess_t)
            elements.append(Spacer(1, 6))

            # Primary Reasoning
            if assessment.primary_reasoning:
                elements.append(Paragraph("<b>Primary Reasoning & Evidence Analysis:</b>", self.styles["SubSectionHeading"]))
                reason_box = Table([[Paragraph(assessment.primary_reasoning, self.styles["BodyDark"])]], colWidths=[504])
                reason_box.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, -1), self.c_light_bg),
                    ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#D1D5DB")),
                    ("PADDING", (0, 0), (-1, -1), 6),
                ]))
                elements.append(reason_box)
                elements.append(Spacer(1, 6))

            # Structured Precursor Extracted Entities
            if assessment.structured_precursor:
                sp = assessment.structured_precursor
                elements.append(Paragraph("<b>Structured Precursor Entities Extracted:</b>", self.styles["SubSectionHeading"]))
                entity_rows = [
                    [
                        Paragraph("Entity Dimension", self.styles["TableHead"]),
                        Paragraph("Extracted Observation", self.styles["TableHead"]),
                    ],
                    [
                        Paragraph("Energy / Hazard Source", self.styles["TableCell"]),
                        Paragraph(str(sp.get("hazard_source") or "UNSPECIFIED"), self.styles["TableCell"]),
                    ],
                    [
                        Paragraph("Failed / Degraded Barrier", self.styles["TableCell"]),
                        Paragraph(str(sp.get("barrier_failure") or "UNSPECIFIED"), self.styles["TableCell"]),
                    ],
                    [
                        Paragraph("Operational Activity", self.styles["TableCell"]),
                        Paragraph(str(sp.get("activity") or "UNSPECIFIED"), self.styles["TableCell"]),
                    ],
                    [
                        Paragraph("Equipment / Asset", self.styles["TableCell"]),
                        Paragraph(str(sp.get("equipment") or "UNSPECIFIED"), self.styles["TableCell"]),
                    ],
                ]
                ent_t = Table(entity_rows, colWidths=[160, 344])
                ent_t.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), self.c_accent_bg),
                    ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                    ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
                    ("TOPPADDING", (0, 0), (-1, -1), 3),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ]))
                elements.append(ent_t)
        else:
            elements.append(Paragraph("<i>No AI screening assessment associated with this report.</i>", self.styles["BodyDark"]))
        elements.append(Spacer(1, 10))

        # 3. Life-Saving Rules Mapping
        elements.append(Paragraph("3. Life-Saving Rules (IOGP Report 459) Association", self.styles["SectionHeading"]))
        if lsr_mappings:
            lsr_rows = [
                [
                    Paragraph("LSR Code", self.styles["TableHead"]),
                    Paragraph("Confidence", self.styles["TableHead"]),
                    Paragraph("Mapping Source", self.styles["TableHead"]),
                ]
            ]
            for m in lsr_mappings:
                rule_c = getattr(m, 'rule_code', getattr(m, 'lsr_code', str(m)))
                conf_s = getattr(m, 'confidence_score', getattr(m, 'mapping_confidence', 1.0))
                lsr_rows.append([
                    Paragraph(f"<b>{rule_c}</b>", self.styles["TableCell"]),
                    Paragraph(f"{conf_s:.2f}", self.styles["TableCellCenter"]),
                    Paragraph(str(getattr(m, 'mapping_source', 'AI_HEURISTIC')), self.styles["TableCell"]),
                ])
            lsr_t = Table(lsr_rows, colWidths=[150, 100, 254])
            lsr_t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), self.c_accent_bg),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]))
            elements.append(lsr_t)
        else:
            elements.append(Paragraph("<i>No Life-Saving Rule violations identified for this event.</i>", self.styles["BodyDark"]))
        elements.append(Spacer(1, 10))

        # 4. Related Actions & Investigation Case
        elements.append(Paragraph("4. Assigned HSE Actions & Investigation Links", self.styles["SectionHeading"]))
        if related_actions:
            act_rows = [
                [
                    Paragraph("Action Title", self.styles["TableHead"]),
                    Paragraph("Priority", self.styles["TableHead"]),
                    Paragraph("Status", self.styles["TableHead"]),
                    Paragraph("Assigned To", self.styles["TableHead"]),
                ]
            ]
            for a in related_actions:
                pri_str = a.priority.value if hasattr(a.priority, 'value') else str(a.priority)
                st_str = a.status.value if hasattr(a.status, 'value') else str(a.status)
                act_title = getattr(a, 'action_title', getattr(a, 'title', 'HSE Action'))
                assigned = getattr(a, 'assigned_to', getattr(a, 'target_role', 'UNASSIGNED'))
                act_rows.append([
                    Paragraph(f"<b>{act_title}</b>", self.styles["TableCell"]),
                    Paragraph(pri_str, self.styles["TableCellCenter"]),
                    Paragraph(st_str, self.styles["TableCellCenter"]),
                    Paragraph(assigned or "UNASSIGNED", self.styles["TableCell"]),
                ])
            act_t = Table(act_rows, colWidths=[204, 70, 90, 140])
            act_t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), self.c_accent_bg),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]))
            elements.append(act_t)
        else:
            elements.append(Paragraph("<i>No specific HSE actions assigned to this report.</i>", self.styles["BodyDark"]))

        if related_case:
            elements.append(Spacer(1, 6))
            case_info = f"<b>Active Formal Investigation Case:</b> {related_case.title} (Case #{str(related_case.id)[:8].upper()} • Status: {related_case.status.value if hasattr(related_case.status, 'value') else str(related_case.status)})"
            elements.append(Paragraph(case_info, self.styles["BodyDark"]))

        doc.build(elements, canvasmaker=NumberedCanvas)
        return buffer.getvalue()

    # -------------------------------------------------------------------------
    # 3. HSE CASE INVESTIGATION DOSSIER PDF
    # -------------------------------------------------------------------------
    def generate_case_dossier_pdf(
        self,
        case: HSECase,
        events: Optional[List[HSECaseEvent]] = None,
        actions: Optional[List[HSEActionRecommendation]] = None,
        sources: Optional[List[HSECaseSourceAssociation]] = None,
    ) -> bytes:
        """Generate comprehensive HSE Formal Investigation Case Dossier PDF."""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            leftMargin=54,
            rightMargin=54,
            topMargin=54,
            bottomMargin=54,
        )

        elements = []

        case_num = getattr(case, "case_key", None) or str(case.id)[:8].upper()
        meta_items = [
            ("Case Ref", f"{case_num}"),
            ("Case Type", case.case_type.value if hasattr(case.case_type, 'value') else str(case.case_type)),
            ("Status", case.status.value if hasattr(case.status, 'value') else str(case.status)),
            ("Priority", case.priority.value if hasattr(case.priority, 'value') else str(case.priority)),
            ("Lead Investigator", case.owner or "UNASSIGNED"),
            ("Created At", case.created_at.strftime("%Y-%m-%d %H:%M UTC") if case.created_at else "N/A"),
        ]
        elements.extend(self._build_header_banner(
            title="OIL INDIA LIMITED",
            subtitle=f"HSE FORMAL INVESTIGATION CASE DOSSIER — {case.title}",
            metadata_items=meta_items,
        ))

        # 1. Investigation Scope & Summary
        elements.append(Paragraph("1. Investigation Overview & Summary", self.styles["SectionHeading"]))
        summary_text = case.description or "No formal case description recorded."
        summary_box = Table([[Paragraph(summary_text, self.styles["BodyDarkJustify"])]], colWidths=[504])
        summary_box.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F9FAFB")),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#D1D5DB")),
            ("PADDING", (0, 0), (-1, -1), 8),
        ]))
        elements.append(summary_box)
        elements.append(Spacer(1, 10))

        # 2. Attached Source Intelligence & Evidence
        elements.append(Paragraph("2. Attached Source Intelligence & Precursors", self.styles["SectionHeading"]))
        if sources:
            src_rows = [
                [
                    Paragraph("Source Type", self.styles["TableHead"]),
                    Paragraph("Source Entity Identifier", self.styles["TableHead"]),
                    Paragraph("Attached At", self.styles["TableHead"]),
                ]
            ]
            for s in sources:
                src_type_str = s.source_type.value if hasattr(s.source_type, 'value') else str(s.source_type)
                att_dt = getattr(s, 'attached_at', getattr(s, 'created_at', None))
                att_str = att_dt.strftime("%Y-%m-%d %H:%M") if att_dt else "N/A"
                src_rows.append([
                    Paragraph(src_type_str, self.styles["TableCell"]),
                    Paragraph(f"<b>{s.source_id}</b>", self.styles["TableCell"]),
                    Paragraph(att_str, self.styles["TableCellCenter"]),
                ])
            src_t = Table(src_rows, colWidths=[140, 244, 120])
            src_t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), self.c_accent_bg),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]))
            elements.append(src_t)
        else:
            elements.append(Paragraph("<i>No source intelligence entities linked to this case.</i>", self.styles["BodyDark"]))
        elements.append(Spacer(1, 10))

        # 3. Corrective & Preventive Action Plan
        elements.append(Paragraph("3. Attached Corrective Actions & Resolution Status", self.styles["SectionHeading"]))
        if actions:
            act_rows = [
                [
                    Paragraph("Action Title", self.styles["TableHead"]),
                    Paragraph("Priority", self.styles["TableHead"]),
                    Paragraph("Status", self.styles["TableHead"]),
                    Paragraph("Category", self.styles["TableHead"]),
                ]
            ]
            for a in actions:
                pri_str = a.priority.value if hasattr(a.priority, 'value') else str(a.priority)
                st_str = a.status.value if hasattr(a.status, 'value') else str(a.status)
                cat_str = a.action_category.value if hasattr(a.action_category, 'value') else str(a.action_category)
                act_title = getattr(a, 'action_title', getattr(a, 'title', 'HSE Action'))
                act_rows.append([
                    Paragraph(f"<b>{act_title}</b>", self.styles["TableCell"]),
                    Paragraph(pri_str, self.styles["TableCellCenter"]),
                    Paragraph(st_str, self.styles["TableCellCenter"]),
                    Paragraph(cat_str, self.styles["TableCell"]),
                ])
            act_t = Table(act_rows, colWidths=[194, 70, 90, 150])
            act_t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), self.c_accent_bg),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]))
            elements.append(act_t)
        else:
            elements.append(Paragraph("<i>No corrective actions attached to this case.</i>", self.styles["BodyDark"]))
        elements.append(Spacer(1, 10))

        # 4. Investigation Timeline & Event History
        elements.append(Paragraph("4. Timeline of Investigation Events & Audit History", self.styles["SectionHeading"]))
        if events:
            ev_rows = [
                [
                    Paragraph("Timestamp", self.styles["TableHead"]),
                    Paragraph("Event Type", self.styles["TableHead"]),
                    Paragraph("Actor", self.styles["TableHead"]),
                    Paragraph("Details / Notes", self.styles["TableHead"]),
                ]
            ]
            for e in events[:12]:
                ev_type_str = e.event_type.value if hasattr(e.event_type, 'value') else str(e.event_type)
                actor = getattr(e, 'actor_id', getattr(e, 'actor', 'SYSTEM'))
                note_str = getattr(e, 'rationale', getattr(e, 'notes', '-')) or "-"
                ev_rows.append([
                    Paragraph(e.created_at.strftime("%Y-%m-%d %H:%M") if e.created_at else "N/A", self.styles["TableCell"]),
                    Paragraph(ev_type_str, self.styles["TableCell"]),
                    Paragraph(actor, self.styles["TableCellCenter"]),
                    Paragraph(note_str, self.styles["TableCell"]),
                ])
            ev_t = Table(ev_rows, colWidths=[100, 130, 80, 194])
            ev_t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), self.c_accent_bg),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ]))
            elements.append(ev_t)
        else:
            elements.append(Paragraph("<i>No timeline events recorded.</i>", self.styles["BodyDark"]))

        doc.build(elements, canvasmaker=NumberedCanvas)
        return buffer.getvalue()
