"""API Response, Error, and Pagination Contract Definitions for Phase 11.

Provides standardized, reusable DTOs and metadata envelopes for frontend consumption
and machine-readable API verification.
"""

from datetime import datetime, timezone
from typing import Any, Dict, Generic, List, Optional, TypeVar
from pydantic import BaseModel, Field

API_VERSION: str = "1.0"

T = TypeVar("T")


class ApiMetadata(BaseModel):
    """Metadata describing request traceability, generation timestamp, and API version."""

    request_id: str = Field(
        ...,
        description="Deterministic request identifier for request traceability",
    )
    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Timestamp when the API response was generated by the backend",
    )
    data_as_of: Optional[datetime] = Field(
        None,
        description="Timestamp of latest relevant persisted database state used in the response",
    )
    api_version: str = Field(
        default=API_VERSION,
        description="Authoritative API contract version",
    )


class ApiError(BaseModel):
    """Standardized structured error payload."""

    code: str = Field(
        ...,
        description="Machine-readable error code (e.g., INVALID_DATE_RANGE, RESOURCE_NOT_FOUND)",
    )
    message: str = Field(
        ...,
        description="Human-readable explanation of the error condition",
    )
    details: Optional[Any] = Field(
        default=None,
        description="Additional context, structured validation details, or field-level errors",
    )
    request_id: Optional[str] = Field(
        default=None,
        description="Request identifier associated with the failed operation",
    )


class ApiErrorResponse(BaseModel):
    """Consistent top-level error response envelope."""

    error: ApiError = Field(
        ...,
        description="Structured error details",
    )


class PaginationMetadata(BaseModel):
    """Standardized pagination metadata for list-based responses."""

    limit: int = Field(..., ge=1, description="Maximum number of items requested per page")
    offset: int = Field(..., ge=0, description="Offset index of first item returned")
    returned: int = Field(..., ge=0, description="Actual number of items returned in current response")
    total: int = Field(..., ge=0, description="Total count of matching records across all pages")
    has_next: bool = Field(..., description="Whether additional records exist beyond current page")


class PaginatedResponseEnvelope(BaseModel, Generic[T]):
    """Generic envelope wrapping paginated items, pagination metadata, and response metadata."""

    items: List[T] = Field(default_factory=list, description="List of items for current page")
    pagination: PaginationMetadata = Field(..., description="Pagination metadata")
    metadata: ApiMetadata = Field(..., description="Response metadata and request traceability")
